begin;

-- Replace the broken normalize_greek() translate map with one generated from the same
-- rules as the app/Python normalizer (lowercase -> NFD -> strip combining marks except
-- U+0345 iota subscript -> NFC). We can't do NFD/NFC in Postgres reliably on Supabase,
-- so we use a deterministic translate() map over the Greek/Greek Extended blocks.

create or replace function public.normalize_greek(input_text text)
returns text
language plpgsql
immutable
as $$
declare
  marks_to_strip text := '';
  i int;
  -- Characters whose normalization differs under our canonical normalizer.
  -- Generated by applying the app/Python normalizer to each codepoint in:
  -- - Greek and Coptic: U+0370..U+03FF
  -- - Greek Extended:   U+1F00..U+1FFF
  from_chars text :=
    U&'\0374\037E\0385\0387\0390\03AC\03AD\03AE\03AF\03B0\03CA\03CB\03CC\03CD\03CE\03D3\03D4\1F00\1F01\1F02\1F03\1F04\1F05\1F06\1F07\1F10\1F11\1F12\1F13\1F14\1F15\1F20\1F21\1F22\1F23\1F24\1F25\1F26\1F27\1F30\1F31\1F32\1F33\1F34\1F35\1F36\1F37\1F40\1F41\1F42\1F43\1F44\1F45\1F50\1F51\1F52\1F53\1F54\1F55\1F56\1F57\1F60\1F61\1F62\1F63\1F64\1F65\1F66\1F67\1F70\1F71\1F72\1F73\1F74\1F75\1F76\1F77\1F78\1F79\1F7A\1F7B\1F7C\1F7D\1F80\1F81\1F82\1F83\1F84\1F85\1F86\1F87\1F90\1F91\1F92\1F93\1F94\1F95\1F96\1F97\1FA0\1FA1\1FA2\1FA3\1FA4\1FA5\1FA6\1FA7\1FB0\1FB1\1FB2\1FB4\1FB6\1FB7\1FBE\1FC1\1FC2\1FC4\1FC6\1FC7\1FCD\1FCE\1FCF\1FD0\1FD1\1FD2\1FD3\1FD6\1FD7\1FDD\1FDE\1FDF\1FE0\1FE1\1FE2\1FE3\1FE4\1FE5\1FE6\1FE7\1FED\1FEE\1FEF\1FF2\1FF4\1FF6\1FF7\1FFD';
  to_chars text :=
    U&'\02B9\003B\00A8\00B7\03B9\03B1\03B5\03B7\03B9\03C5\03B9\03C5\03BF\03C5\03C9\03D2\03D2\03B1\03B1\03B1\03B1\03B1\03B1\03B1\03B1\03B5\03B5\03B5\03B5\03B5\03B5\03B7\03B7\03B7\03B7\03B7\03B7\03B7\03B7\03B9\03B9\03B9\03B9\03B9\03B9\03B9\03B9\03BF\03BF\03BF\03BF\03BF\03BF\03C5\03C5\03C5\03C5\03C5\03C5\03C5\03C5\03C9\03C9\03C9\03C9\03C9\03C9\03C9\03C9\03B1\03B1\03B5\03B5\03B7\03B7\03B9\03B9\03BF\03BF\03C5\03C5\03C9\03C9\1FB3\1FB3\1FB3\1FB3\1FB3\1FB3\1FB3\1FB3\1FC3\1FC3\1FC3\1FC3\1FC3\1FC3\1FC3\1FC3\1FF3\1FF3\1FF3\1FF3\1FF3\1FF3\1FF3\1FF3\03B1\03B1\1FB3\1FB3\03B1\1FB3\03B9\00A8\1FC3\1FC3\03B7\1FC3\1FBF\1FBF\1FBF\03B9\03B9\03B9\03B9\03B9\03B9\1FFE\1FFE\1FFE\03C5\03C5\03C5\03C5\03C1\03C1\03C5\03C5\00A8\00A8\0060\1FF3\1FF3\03C9\1FF3\00B4';
begin
  -- Strip combining marks (U+0300..U+036F) except iota subscript (U+0345).
  for i in 768..879 loop
    if i = 837 then
      continue;
    end if;
    marks_to_strip := marks_to_strip || chr(i);
  end loop;

  return translate(
    translate(lower(coalesce(input_text, '')), marks_to_strip, ''),
    from_chars,
    to_chars
  );
end;
$$;

-- Backfill stored normalized columns and generated prefixes.
update public.entries
set greek_normalized = public.normalize_greek(greek)
where greek_normalized is distinct from public.normalize_greek(greek);

update public.lemmata
set headword_normalized = public.normalize_greek(headword_gr)
where headword_normalized is distinct from public.normalize_greek(headword_gr);

commit;

